# **PyTorch Fundamentals**
Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

## Importing

In [72]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to tensors

In [73]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [74]:
scalar.ndim

0

In [75]:
# Get tensor back as Python int
scalar.item()

7

In [76]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [77]:
vector.ndim

1

In [78]:
vector.shape

torch.Size([2])

In [79]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [80]:
MATRIX.ndim

2

In [81]:
MATRIX[1]

tensor([ 9, 10])

In [82]:
MATRIX.shape

torch.Size([2, 2])

In [83]:
# Tensor
TENSOR = torch.tensor([[[1,2,3], 
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [84]:
TENSOR.ndim

3

In [85]:
TENSOR.shape

torch.Size([1, 3, 3])

In [86]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensort full of random numbers and then adjust those random  numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [87]:
# Create a random tensor of shape (3, 4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7377, 0.1564, 0.2526, 0.1136],
        [0.0637, 0.1171, 0.7528, 0.4898],
        [0.5949, 0.7624, 0.8144, 0.5494]])

In [88]:
random_tensor.ndim

2

In [89]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))   # height, width, color channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [90]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [91]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [92]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [93]:
# Use torch.arange()
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [95]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype = None,   # what datatype is the tensor
                                device = None,  # what device is your tensor on
                                requires_grad = False)  # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [96]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [97]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [98]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [99]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [100]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [101]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [102]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [103]:
# Try out PyTorch in-build functions
torch.mul(tensor, 10), torch.add(tensor, 10)

(tensor([10, 20, 30]), tensor([11, 12, 13]))

### Matrix multiplication

Two main ways of performing multiplication in neural networks in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimension** must match:
   * `(3, 2) @ (3, 2)` won't work
   * `(2, 3) @ (3, 2)` will work
   * `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
   * `(2, 3) @ (3, 2)` -> `(2, 2)`

In [104]:
# Element-wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [105]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [106]:
%%time
value = 0 
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [107]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### One of the most commom errors in deep learning: shape errors

In [108]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

#torch.mm(tensor_A, tensor_B)   #RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)    # torch.mm is an alias to torch.matmul     

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**, which switches the axes or dimensions of a given tensor

In [109]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [110]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [111]:
# The matrix multiplication operation works when tensor_B is transposed
torch.matmul(tensor_A, tensor_B.T), torch.matmul(tensor_A, tensor_B.T).shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))

### Finding the min, max, mean, sum etc (tensor aggregation)

In [112]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [113]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [114]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [115]:
# torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [116]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [117]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [118]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [119]:
# Find the position in tensor that has the maximum value with argmax() -> returns index position of target tensor where maximum value occurs
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimension to a target tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [120]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [121]:
# Reshape
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [122]:
# View
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [123]:
# Changing z changes x (because a view of a tensor shares the memory as the original imput)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [124]:
# Stack tensors
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [125]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [126]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [127]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [129]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [132]:
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [133]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))     # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)    # shitts axis 0->1, 1->2, 2->0

x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [135]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [136]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [138]:
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [140]:
x[0][0][0], x[0, 0, 0]

(tensor(1), tensor(1))

In [141]:
x[0][1][1]

tensor(5)

In [142]:
# You can use ":" to select all of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [143]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [144]:
x[:, 1, 1]

tensor([5])

In [145]:
x[0, 0, :]

tensor([1, 2, 3])

In [150]:
x[0][2][2], x[:, :, 2]

(tensor(9), tensor([[3, 6, 9]]))

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)    # when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [154]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [155]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [156]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [157]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again -> again -> again -> ...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [216]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
random_tensor_A, random_tensor_B, random_tensor_A == random_tensor_B

(tensor([[0.4114, 0.4832, 0.8062, 0.8800],
         [0.3923, 0.3486, 0.2209, 0.0924],
         [0.7756, 0.3863, 0.6026, 0.1413]]),
 tensor([[0.6761, 0.1013, 0.5344, 0.0642],
         [0.9151, 0.6298, 0.9045, 0.8883],
         [0.4421, 0.7842, 0.5095, 0.1087]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [221]:
# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

random_tensor_C, random_tensor_D, random_tensor_C == random_tensor_D

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorchy working behind the scenes

* Use Google Colab
* Use your own (NVIDIA) GPU     (Since I have AMD GPU, this part of the code must be ran outside local file, for example Google Colab)
* Use cloud computing - GCP, AWS, Azure, etc.


In [ ]:
"""
!nvidia-smi

# Check for GPU access with PyTorch
torch.cuda.is_available()

# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

# Count number of devices
torch.cuda.device_count()

# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3], device = "cpu")
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

# Moving tensor back to CPU
# If tensor is on GPU, can't transform it to NumPy
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu
"""

## Excercises

0