# **PyTorch Fundamentals**
Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

## Importing

In [83]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to tensors

In [84]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [85]:
scalar.ndim

0

In [86]:
# Get tensor back as Python int
scalar.item()

7

In [87]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [88]:
vector.ndim

1

In [89]:
vector.shape

torch.Size([2])

In [90]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [91]:
MATRIX.ndim

2

In [92]:
MATRIX[1]

tensor([ 9, 10])

In [93]:
MATRIX.shape

torch.Size([2, 2])

In [94]:
# Tensor
TENSOR = torch.tensor([[[1,2,3], 
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [95]:
TENSOR.ndim

3

In [96]:
TENSOR.shape

torch.Size([1, 3, 3])

In [97]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensort full of random numbers and then adjust those random  numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [98]:
# Create a random tensor of shape (3, 4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6340, 0.6817, 0.5660, 0.0797],
        [0.4290, 0.3474, 0.9835, 0.6231],
        [0.3729, 0.5166, 0.3879, 0.6420]])

In [99]:
random_tensor.ndim

2

In [100]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))   # height, width, color channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [101]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [102]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [103]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [104]:
# Use torch.arange()
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [106]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype = None,   # what datatype is the tensor
                                device = None,  # what device is your tensor on
                                requires_grad = False)  # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [107]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [108]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [109]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [110]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [111]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [112]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [113]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [115]:
# Try out PyTorch in-build functions
torch.mul(tensor, 10), torch.add(tensor, 10)

(tensor([10, 20, 30]), tensor([11, 12, 13]))

### Matrix multiplication

Two main ways of performing multiplication in neural networks in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimension** must match:
   * `(3, 2) @ (3, 2)` won't work
   * `(2, 3) @ (3, 2)` will work
   * `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
   * `(2, 3) @ (3, 2)` -> `(2, 2)`

In [ ]:
# Element-wise multiplication
tensor * tensor

In [117]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [118]:
%%time
value = 0 
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 7.02 ms


tensor(14)

In [119]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### One of the most commom errors in deep learning: shape errors

In [125]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

#torch.mm(tensor_A, tensor_B)   #RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)    # torch.mm is an alias to torch.matmul     

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**, which switches the axes or dimensions of a given tensor

In [124]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [123]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [127]:
# The matrix multiplication operation works when tensor_B is transposed
torch.matmul(tensor_A, tensor_B.T), torch.matmul(tensor_A, tensor_B.T).shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))